### PR TITLE
Added PhoenixTool

### PR DESCRIPTION
**Pull request by Titokhan**

### CODE REVIEW

**Review by penglish2 — APPROVED** [review]
Completely missed that one, thank yoU!

**Comment by Titokhan** [comment]
Welcome!

**Comment by Titokhan** [comment]
Umm... sorry to bother you, but the PR isn't merged yet.

:(

**Comment by penglish2** [comment]
Dang, sorry about that. I'm still new to Github, and I did this through the GUI. I didn't realize that the approval didn't also merge your PR!

**Comment by Titokhan** [comment]
Not an issue 😃 

I guess we can also mention andyp's other tools intended for legacy Award and AMI bioses; they are mainly intended for SLIC modding, but can be adapted as DSDT and/or other ACPI mods as well.

**Pull request merged**
